accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "accounts"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #token
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html' , success_url=reverse_lazy('accounts:password_change_done')), name='change_password'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),name='password_change_done'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html' , success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html' , success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subscription.urls',namespace='subscription')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "subscription Admin"
admin.site.site_title = "subscription Portal"
admin.site.index_title = "subscription Portal"

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    active = models.BooleanField(default=True)
    email_confirmed = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = '1. User'

subscription/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.

PAYMENT_TYPE = (
    ("PAY", "PAYPAL"),
    ("STR", "STRIPS"),
)

class Subscription(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()

    def __str__(self):
        return self.name
    
class Payments(models.Model):
    subscription = models.ForeignKey(Subscription,  on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_type =  models.CharField(max_length=3,choices=PAYMENT_TYPE)
    metadata = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'] = forms.EmailField(
            label=_("E-mail"), max_length=75)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class RegisterForm(UserCreationForm):
    username = forms.CharField(label="",
                               max_length=32, help_text="<small id='emailHelp' class='form-text text-muted'>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    first_name = forms.CharField(label="",
                                 max_length=32, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label="",
                                max_length=32, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    email = forms.EmailField(label="",
                             max_length=50, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label="", help_text="<small><ul class='form-text text-muted'><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul></small>",
                                max_length=40, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label="", help_text="<small class='form-text text-muted'>Enter the same password as before, for verification.</small>",
                                max_length=40, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
    class Meta:
        model = get_user_model()
        fields = ('email', 'username','first_name','last_name')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for fieldname in self.fields:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ''

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate , login
from django.contrib.auth.models import User
from accounts.forms import RegisterForm
from django.views import View, generic
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
User = get_user_model()
#token import
from accounts.utils.email import send_account_confirmation_email
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode    
from accounts.token import account_activation_token
from subscription.models import Payments 

def home(request):
    try:
        payment = Payments.objects.filter(user=request.user)
    except:
        payment = None
    return render(request, 'accounts/home.html',{'payment':payment})

class RegisterView(generic.CreateView):
    template_name = 'accounts/register.html'
    form_class = RegisterForm
    def form_valid(self, form):
        user = form.save()
        send_account_confirmation_email(self.request, user)
        login(self.request, user)
        return super(RegisterView, self).form_valid(form)
    def get_success_url(self):
        next_url = self.request.POST.get('next', None)
        if next_url:
            return "%s" % (next_url)
        else:
            return reverse_lazy('accounts:login')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Register'
        return context

def activate(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64)).decode('utf-8')
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.email_confirmed = True
        user.save()
        return redirect('accounts:login')
    else:
        return redirect('accounts:login')

templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 mb-4">
    <h2 class="text-muted">Change Password</h2>
</div>
<div class="col-md-6 offset-md-3 mb-4">
    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Change</button>
    </form>
</div>
{% endblock content %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 mb-4">
    <h2 class="text-muted">Edit Profile</h2>
</div>
<div class="col-md-6 offset-md-3 mb-4">
    <form action="{% url 'edit_profile' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary mb-3">Update</button>
        <p><a href="{% url 'change_password' %}">Click Here</a> To Change Your Password </p>
    </form>
</div>
{% endblock content %}

templates/accounts/home.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endif %}

<div class="row">

  <div class="card col-3 mt-4">
    <h5 class="card-header">User Information</h5>
    <div class="card-body">
      <h5 class="card-title"><b>Name:</b> {{ user.first_name }} {{ user.last_name }}</h5>
      <h5 class="card-title"><b>Username:</b> {{ user.username }}</h5>
      <h5 class="card-title"><b>Email:</b> {{ user.email }}</h5>
      <a href="{% url 'accounts:change_password' %}" class="btn btn-primary">Change Password</a>
    </div>
  </div>


<div class="card text-center mt-4 col-9">
    <div class="card-header"> <h2> Subscription List </h2> </div>
    <div class="card-body">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Subscription Name</th>
                <th scope="col">Price</th>
                <th scope="col">Payment Type</th>
                <th scope="col">Date Time</th>
              </tr>
            </thead>
            <tbody>
              {% for pay in payment %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{pay.subscription}}</td>
                <td>{{pay.subscription.price}}</td>
                <td>{{pay.get_payment_type_display }}</td>
                <td>{{pay.created_at}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
    <div class="card-footer text-muted"></div>
</div>
</div>
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 text-muted">
    <h2>User Login</h2>
</div>
<div class="col-md-6 offset-md-3">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter Password">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
        </div>
        <button type="submit" class="btn btn-secondary mb-3">Login</button>
        <p>Forgot password ??<a href="{% url 'accounts:password_reset' %}"> Click Here</a> To Reset</p>
    </form>
</div>
{% endblock content %}

templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 text-muted">
    <h2>Password Change Succesfully</h2>
</div>

        <p>
            please login again
        </p>
    

{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 mb-4">
    <h2 class="text-muted">Register</h2>
</div>
<div class="col-md-6 offset-md-3 mb-4">
    <form action="{% url 'accounts:register' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Register</button>
    </form>
</div>
{% endblock content %}