accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "accounts"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #token
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html' , success_url=reverse_lazy('accounts:password_change_done')), name='change_password'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),name='password_change_done'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html' , success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html' , success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subscription.urls',namespace='subscription')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "subscription Admin"
admin.site.site_title = "subscription Portal"
admin.site.index_title = "subscription Portal"

subscription/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy

app_name = 'subscription'

urlpatterns = [

    path('', views.index, name="home"),
    path('details/<int:id>', views.details, name="details"),
    path('payment', views.payment, name="payment"),
    path('checkout/', views.CheckoutSession.as_view(), name='checkout'),
    path('checkout-success/', views.CheckoutSuccess.as_view(),name='checkout_success'),
    path('checkout-cancel/', views.CheckoutCancel.as_view(), name='checkout_cancel'),

]

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Home</title>
    <style>
        .errorlist{
            color:red;
        }
    </style>
</head>

<body>
    <!-- navigation bar -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'subscription:home' %}">Subscription App</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:home' %}">{{user.username}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- end of navigation bar -->

    <!-- main content -->
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    <!-- end of main content -->


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

templates/checkout_cancel.html
{% extends "base.html" %}
{% block title %}| Checkout Canceled{% endblock title %}

{% block content %}
<div class="container">
  <h1 class="my-3">Checkout Canceled</h1>
</div>

{% endblock %}

templates/checkout_success.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="my-3">Checkout Success</h1>
</div>

{% endblock %}

templates/details.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-5">

    <div class="card text-center">
        <div class="card-header"></div>
            <div class="card-body">
                <h5 class="card-title">Package Name : {{subscrip.name}}</h5>
                <h5 class="card-title">price : {{subscrip.price}}</h5>
            
            </div>
        
        <div class="col-4 mx-auto">
        <div id="paypal-button-container">
            <!-- Include the PayPal JavaScript SDK -->
            <script src="https://www.paypal.com/sdk/js?client-id=AQ6oVBBo02Ft5CaQe9l27BjayUxJHf0vCS2YpAmbvNekU3oI0qeBwVr77c_MkVI65XZYu-TUM5D0aFSs&currency=USD"></script>
            <script>
                // Render the PayPal button into #paypal-button-container

                function getCookie(name) {
                    let cookieValue = null;
                    if (document.cookie && document.cookie !== '') {
                        const cookies = document.cookie.split(';');
                        for (let i = 0; i < cookies.length; i++) {
                            const cookie = cookies[i].trim();
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                const csrftoken = getCookie('csrftoken');

                var total = '{{subscrip.price}}'
                var package_id = '{{subscrip.id}}'
                var user = '{{user.id}}'
                var payment_type = 'PAY'

                {% comment %} function paymentOrder(){
                    var url = "{% url 'subscription:payment' %}"
                    fetch(url,{
                        method: "POST",
                        headers:{
                            'Content-type':'application/json',
                            'X-CSRFToken': csrftoken
                        },
                        body:JSON.stringify({'package_id':package_id,'user':user,'payment_type':payment_type})
                    })
                } {% endcomment %}
                
                paypal.Buttons({

                    // Set up the transaction
                    createOrder: function(data, actions) {
                        return actions.order.create({
                            purchase_units: [{
                                amount: {
                                    value: total
                                }
                            }]
                        });
                    },

                    // Finalize the transaction
                    onApprove: function(data, actions) {
                        return actions.order.capture().then(function(orderData) {
                            // Successful capture! For demo purposes:
                            
                            var url = "{% url 'subscription:payment' %}"
                            fetch(url,{
                                method: "POST",
                                headers:{
                                    'Content-type':'application/json',
                                    'X-CSRFToken': csrftoken
                                },
                                body:JSON.stringify({'package_id':package_id,'user':user,'payment_type':payment_type,'orderData':orderData})
                            })
                            
                            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                            var transaction = orderData.purchase_units[0].payments.captures[0];
                            alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                            // Replace the above to show a success message within this page, e.g.
                            // const element = document.getElementById('paypal-button-container');
                            // element.innerHTML = '';
                            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                            // Or go to another URL:  actions.redirect('thank_you.html');
                        });
                    }


                }).render('#paypal-button-container');
            </script>
        </div>
        </div>
        <div class="col-4 mx-auto mb-2">
            <!-- This should bring me to Stripe payment -->
            <form action="{% url 'subscription:checkout' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="course" value="{{subscrip.id}}">
                <button class="btn btn-success btn-block"><i class="fab fa-stripe fa-2x"></i></button>
            </form>
        </div>
        <div class="card-footer text-muted"></div>
      
      

</div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-5">
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Package</th>
        <th scope="col">Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
    {% for sub in subscrip %}
      <tr>
        <td>{{sub.name}}</td>
        <td>{{sub.price}}</td>
        <td>
          <a  href="{% url 'subscription:details' sub.id %}"  class="btn btn-success"><i class="fa fa-shopping-cart"></i> Buy </a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}